/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NLW Conect
 * OpenAPI spec version: 0.0.1
 */
export type PostSubscriptionsBody = {
  name: string;
  email: string;
  /** @nullable */
  referrerId?: string | null;
};

export type PostSubscriptions201 = {
  subscriberId: string;
};

/**
 * @nullable
 */
export type GetInvitesSubscriberId302 = typeof GetInvitesSubscriberId302[keyof typeof GetInvitesSubscriberId302] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInvitesSubscriberId302 = {
  null: 'null',
} as const;

export type GetInvitesSubscriberIdRankingClicks200 = {
  count: number;
};

export type GetInvitesSubscriberIdRankingCount200 = {
  count: number;
};

export type GetInvitesSubscriberIdRankingPosition200 = {
  /** @nullable */
  position: number | null;
};

export type GetRanking200RankingItem = {
  id: string;
  name: string;
  email: string;
  score: number;
};

export type GetRanking200 = {
  ranking: GetRanking200RankingItem[];
};



/**
 * @summary Subscribe someone to an event
 */
export const getPostSubscriptionsUrl = () => {


  return `http://localhost:3333/subscriptions`
}

export const postSubscriptions = async (postSubscriptionsBody: PostSubscriptionsBody, options?: RequestInit): Promise<PostSubscriptions201> => {
  
  const res = await fetch(getPostSubscriptionsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postSubscriptionsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostSubscriptions201 = body ? JSON.parse(body) : {}

  return data
}



/**
 * @summary Access an invite link and redirect user
 */
export const getGetInvitesSubscriberIdUrl = (subscriberId: string,) => {


  return `http://localhost:3333/invites/${subscriberId}`
}

export const getInvitesSubscriberId = async (subscriberId: string, options?: RequestInit): Promise<unknown> => {
  
  const res = await fetch(getGetInvitesSubscriberIdUrl(subscriberId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: unknown = body ? JSON.parse(body) : {}

  return data
}



/**
 * @summary Get the number of clicks on an invite link
 */
export const getGetInvitesSubscriberIdRankingClicksUrl = (subscriberId: string,) => {


  return `http://localhost:3333/invites/${subscriberId}/ranking/clicks`
}

export const getInvitesSubscriberIdRankingClicks = async (subscriberId: string, options?: RequestInit): Promise<GetInvitesSubscriberIdRankingClicks200> => {
  
  const res = await fetch(getGetInvitesSubscriberIdRankingClicksUrl(subscriberId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetInvitesSubscriberIdRankingClicks200 = body ? JSON.parse(body) : {}

  return data
}



/**
 * @summary Get the number of invites on an invite link
 */
export const getGetInvitesSubscriberIdRankingCountUrl = (subscriberId: string,) => {


  return `http://localhost:3333/invites/${subscriberId}/ranking/count`
}

export const getInvitesSubscriberIdRankingCount = async (subscriberId: string, options?: RequestInit): Promise<GetInvitesSubscriberIdRankingCount200> => {
  
  const res = await fetch(getGetInvitesSubscriberIdRankingCountUrl(subscriberId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetInvitesSubscriberIdRankingCount200 = body ? JSON.parse(body) : {}

  return data
}



/**
 * @summary Get the position of a subscriber in the ranking
 */
export const getGetInvitesSubscriberIdRankingPositionUrl = (subscriberId: string,) => {


  return `http://localhost:3333/invites/${subscriberId}/ranking/position`
}

export const getInvitesSubscriberIdRankingPosition = async (subscriberId: string, options?: RequestInit): Promise<GetInvitesSubscriberIdRankingPosition200> => {
  
  const res = await fetch(getGetInvitesSubscriberIdRankingPositionUrl(subscriberId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetInvitesSubscriberIdRankingPosition200 = body ? JSON.parse(body) : {}

  return data
}



/**
 * @summary Get the ranking of subscribers
 */
export const getGetRankingUrl = () => {


  return `http://localhost:3333/ranking`
}

export const getRanking = async ( options?: RequestInit): Promise<GetRanking200> => {
  
  const res = await fetch(getGetRankingUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetRanking200 = body ? JSON.parse(body) : {}

  return data
}



